### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by redpois0n** [imgbi/imgbi-client#3]
Hello, I am writing a screenshot application with modules to upload to several different image hosting sites.

I am writing the imgbi module which will invoke the imgbi-client.

I have successfully installed node.js and npm, and installed imgbi-client correctly.

But when I run imgbi-client -i file.png, I get the following error:

```
$ imgbi-client -i test.png
 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

I installed using the command in your README.md

I also cannot download files

```$ imgbi-client -d 'https://img.bi/#/gVRsxhe!QID5Zgzrq_PgWF2UmQSzWXtA0NNHXAJ-rnIQWd-o'
ERROR: Error: 404```

I can visit and view the image at the URL specified by the -d argument

Any help would be appreciated, best regards

**Comment by komachi** [comment]
Upload works for me with no errors, are you still having this issue? Downloading (and removing) fixed in 0.0.5.

**Comment by redpois0n** [comment]
On Windows, it will not parse arguments correctly. Just updated to 0.0.5.

```
$ imgbi-client -i image.jpg
ERROR: Error: Command failed: Invalid Parameter - -set
```

Note that the file exists.

If I do the same on Linux, I still get the following error:

```
$ imgbi-client -i image.jpg

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by komachi** [comment]
Try to install imagemagick. I probably should move from it to something pure JS.

**Comment by redpois0n** [comment]
Installed imagemagick on Linux and it works now, but it still fails to parse arguments on Windows.

```
$ imgbi-client -i example.jpg
ERROR: Error: Command failed: Invalid Parameter - -set
```

I've tried with /i instead and --image but seems really weird. Also installed imagemagick there.

**Comment by komachi** [comment]
That error coming from imagemagick. Maybe it's not in your `%PATH%` or something like that?
